import {
  User,
  Client,
  Vehicle,
  Appointment,
  Repair,
  Service,
  Part,
  Invoice,
  Payment,
  Expense,
} from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr-1',
    name: 'Marcus Vance',
    email: 'owner@autocare.com',
    role: 'ADMIN',
    is_active: true,
    phone: '+1 (555) 234-5678',
    avatar_url: '/src/assets/images/autocare_owner_avatar_1790162967608.jpg',
    created_at: '2025-01-10T08:00:00Z',
  },
  {
    id: 'usr-2',
    name: 'Alex Rivera',
    email: 'mechanic@autocare.com',
    role: 'GARAGISTE',
    is_active: true,
    phone: '+1 (555) 345-6789',
    avatar_url: '/src/assets/images/autocare_mechanic_avatar_1790162978810.jpg',
    created_at: '2025-02-15T09:30:00Z',
  },
  {
    id: 'usr-3',
    name: 'Sam Kowalski',
    email: 'sam.tech@autocare.com',
    role: 'GARAGISTE',
    is_active: true,
    phone: '+1 (555) 456-7890',
    avatar_url: '',
    created_at: '2025-03-01T10:00:00Z',
  },
];

export const INITIAL_CLIENTS: Client[] = [
  {
    id: 'cli-1',
    first_name: 'Elena',
    last_name: 'Rostova',
    email: 'elena.rostova@example.com',
    phone: '+1 (555) 789-0123',
    address: '742 Evergreen Terrace, Springfield',
    notes: 'Prefers OEM parts for her BMW. Key drop-off early mornings.',
    created_at: '2025-05-12T10:00:00Z',
  },
  {
    id: 'cli-2',
    first_name: 'David',
    last_name: 'Kim',
    email: 'david.kim@example.com',
    phone: '+1 (555) 890-1234',
    address: '104 Industrial Parkway, Suite 4',
    notes: 'Fleet commuter vehicle, requires itemized tax invoices.',
    created_at: '2025-06-18T14:20:00Z',
  },
  {
    id: 'cli-3',
    first_name: 'Sarah',
    last_name: 'Jenkins',
    email: 'sarah.j@example.com',
    phone: '+1 (555) 901-2345',
    address: '88 Meadowbrook Road, Apt 2B',
    notes: 'Brake squeal reported at low speeds.',
    created_at: '2025-07-04T11:15:00Z',
  },
  {
    id: 'cli-4',
    first_name: 'Robert',
    last_name: 'Chen',
    email: 'robert.chen@example.com',
    phone: '+1 (555) 012-3456',
    address: '512 Oakwood Boulevard',
    notes: 'Scheduled for complete 60,000 km service inspection.',
    created_at: '2025-08-20T09:00:00Z',
  },
  {
    id: 'cli-5',
    first_name: 'Amira',
    last_name: 'Benali',
    email: 'amira.benali@example.com',
    phone: '+1 (555) 123-9876',
    address: '320 Highland Avenue',
    notes: 'Check engine light on; suspected O2 sensor or catalytic efficiency.',
    created_at: '2025-09-02T16:45:00Z',
  },
];

export const INITIAL_VEHICLES: Vehicle[] = [
  {
    id: 'veh-1',
    client_id: 'cli-1',
    registration_number: '7ABC892',
    brand: 'BMW',
    model: '330i xDrive',
    year: 2021,
    mileage: 48500,
    fuel_type: 'GASOLINE',
    vin: 'WBA33AY08MFL12345',
    owner_name: 'Elena Rostova',
    notes: 'All-wheel drive sedan, regular synthetic service history.',
    created_at: '2025-05-12T10:15:00Z',
  },
  {
    id: 'veh-2',
    client_id: 'cli-2',
    registration_number: '5XYZ341',
    brand: 'Audi',
    model: 'Q5 45 TFSI Quattro',
    year: 2020,
    mileage: 72100,
    fuel_type: 'GASOLINE',
    vin: 'WAUZZZF45LA098765',
    owner_name: 'David Kim',
    notes: 'Slight transmission shudder on cold mornings.',
    created_at: '2025-06-18T14:30:00Z',
  },
  {
    id: 'veh-3',
    client_id: 'cli-3',
    registration_number: '8TRK119',
    brand: 'Mercedes-Benz',
    model: 'C300 4MATIC',
    year: 2019,
    mileage: 89400,
    fuel_type: 'GASOLINE',
    vin: 'WDD2050401R543210',
    owner_name: 'Sarah Jenkins',
    notes: 'Front brake wear indicator light tripped.',
    created_at: '2025-07-04T11:30:00Z',
  },
  {
    id: 'veh-4',
    client_id: 'cli-4',
    registration_number: '9MNO883',
    brand: 'Volkswagen',
    model: 'Golf GTI MK8',
    year: 2022,
    mileage: 34200,
    fuel_type: 'GASOLINE',
    vin: 'WVWZZZCDZPW112233',
    owner_name: 'Robert Chen',
    notes: 'Performance pack with limited slip differential.',
    created_at: '2025-08-20T09:20:00Z',
  },
  {
    id: 'veh-5',
    client_id: 'cli-5',
    registration_number: '3KPL402',
    brand: 'Toyota',
    model: 'RAV4 Hybrid AWD',
    year: 2023,
    mileage: 26800,
    fuel_type: 'HYBRID',
    vin: '2T3C1RFV5PC998877',
    owner_name: 'Amira Benali',
    notes: 'Hybrid battery diagnostic healthy, regular service.',
    created_at: '2025-09-02T17:00:00Z',
  },
];

export const INITIAL_SERVICES: Service[] = [
  {
    id: 'srv-1',
    name: 'Synthetic Oil & Filter Service',
    description: 'Full synthetic OEM-grade oil change, premium filter, 21-point visual inspection and fluid top-off.',
    price: 119.0,
    estimated_minutes: 45,
    category: 'Maintenance',
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'srv-2',
    name: 'Complete Brake Pad & Rotor Service (Axle)',
    description: 'Precision pad fitting, rotor replacement or resurfacing, caliper slide greasing and hydraulic bleed check.',
    price: 340.0,
    estimated_minutes: 90,
    category: 'Brakes',
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'srv-3',
    name: 'Comprehensive Computer Diagnostic Scan',
    description: 'OBD-II ECU/TCU/ABS full system readout, live sensor telemetry log, fault code root cause analysis.',
    price: 85.0,
    estimated_minutes: 40,
    category: 'Diagnostics',
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'srv-4',
    name: 'Automated Transmission Fluid Flush',
    description: 'High-pressure exchange of ATF fluid, internal filter clean/replacement and temperature adaptation reset.',
    price: 260.0,
    estimated_minutes: 75,
    category: 'Drivetrain',
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'srv-5',
    name: '4-Wheel Laser Precision Alignment',
    description: 'Computerized laser alignment of camber, caster and toe angles for reduced tire wear and optimal handling.',
    price: 135.0,
    estimated_minutes: 60,
    category: 'Suspension',
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'srv-6',
    name: 'Cooling System Flush & Pressure Leak Test',
    description: 'Evacuate old coolant, chemical reverse flush, refill with long-life coolant and pressure test up to 1.5 bar.',
    price: 165.0,
    estimated_minutes: 50,
    category: 'Cooling',
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'srv-7',
    name: 'Spark Plug & Ignition Coil Renewal',
    description: 'Remove worn plugs, check cylinder bore, install laser iridium plugs torqued to manufacturer spec.',
    price: 180.0,
    estimated_minutes: 60,
    category: 'Engine',
    created_at: '2025-01-01T00:00:00Z',
  },
];

export const INITIAL_PARTS: Part[] = [
  {
    id: 'prt-1',
    name: 'Bosch Premium Spin-On Oil Filter',
    part_number: 'BOS-OF-3320',
    category: 'Filters',
    current_stock: 18,
    minimum_stock: 8,
    purchase_price: 8.5,
    selling_price: 19.5,
    location: 'Bay 1 - Shelf A3',
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prt-2',
    name: 'Brembo Ceramic Front Brake Pads',
    part_number: 'BRM-P85020N',
    category: 'Brakes',
    current_stock: 3, // LOW STOCK
    minimum_stock: 6,
    purchase_price: 48.0,
    selling_price: 98.0,
    location: 'Bay 2 - Shelf B1',
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prt-3',
    name: 'Castrol EDGE 5W-30 LL Full Synthetic (5L)',
    part_number: 'CAS-EDGE-5W30',
    category: 'Fluids',
    current_stock: 22,
    minimum_stock: 10,
    purchase_price: 29.0,
    selling_price: 58.0,
    location: 'Storage Cage - Drum Rack',
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prt-4',
    name: 'NGK Laser Iridium Spark Plug',
    part_number: 'NGK-SILZKBR8D8S',
    category: 'Ignition',
    current_stock: 4, // LOW STOCK
    minimum_stock: 12,
    purchase_price: 9.5,
    selling_price: 24.0,
    location: 'Bay 1 - Drawer 4',
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prt-5',
    name: 'Continental Multi-Rib Serpentine Belt',
    part_number: 'CNT-6PK1875',
    category: 'Belts',
    current_stock: 7,
    minimum_stock: 5,
    purchase_price: 21.0,
    selling_price: 49.0,
    location: 'Bay 3 - Pegboard 2',
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prt-6',
    name: 'DOT 4 High Performance Brake Fluid (1L)',
    part_number: 'MOT-DOT4-1L',
    category: 'Fluids',
    current_stock: 2, // LOW STOCK
    minimum_stock: 8,
    purchase_price: 7.5,
    selling_price: 18.0,
    location: 'Chemical Cabinet C',
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 'prt-7',
    name: 'Mann Activated Charcoal Cabin Filter',
    part_number: 'MAN-CUK2939',
    category: 'Filters',
    current_stock: 12,
    minimum_stock: 6,
    purchase_price: 14.0,
    selling_price: 32.0,
    location: 'Bay 1 - Shelf A2',
    created_at: '2025-01-01T00:00:00Z',
  },
];

const today = new Date().toISOString().split('T')[0];
const yesterday = new Date(Date.now() - 86400000).toISOString().split('T')[0];
const tomorrow = new Date(Date.now() + 86400000).toISOString().split('T')[0];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'app-1',
    client_id: 'cli-1',
    vehicle_id: 'veh-1',
    date: today,
    time_slot: '09:00 - 10:30',
    reason: 'Oil service and front suspension check before road trip',
    status: 'IN_PROGRESS',
    notes: 'Customer waiting in lounge',
    created_at: `${yesterday}T14:00:00Z`,
  },
  {
    id: 'app-2',
    client_id: 'cli-3',
    vehicle_id: 'veh-3',
    date: today,
    time_slot: '11:00 - 12:30',
    reason: 'Front brake grinding and sensor warning',
    status: 'CONFIRMED',
    notes: 'Left key with receptionist',
    created_at: `${yesterday}T16:30:00Z`,
  },
  {
    id: 'app-3',
    client_id: 'cli-5',
    vehicle_id: 'veh-5',
    date: today,
    time_slot: '14:00 - 15:30',
    reason: 'Check engine light diagnostic scan & hybrid health check',
    status: 'PENDING',
    notes: 'Customer will call before arrival',
    created_at: `${today}T08:15:00Z`,
  },
  {
    id: 'app-4',
    client_id: 'cli-2',
    vehicle_id: 'veh-2',
    date: tomorrow,
    time_slot: '10:00 - 11:30',
    reason: 'Transmission fluid service & 70,000 km checkup',
    status: 'CONFIRMED',
    notes: 'Requested loaner vehicle if possible',
    created_at: `${yesterday}T11:00:00Z`,
  },
  {
    id: 'app-5',
    client_id: 'cli-4',
    vehicle_id: 'veh-4',
    date: yesterday,
    time_slot: '13:00 - 14:30',
    reason: 'Spark plug change and dynamic wheel alignment',
    status: 'COMPLETED',
    notes: 'Job completed smoothly, test driven 5km',
    created_at: '2025-09-20T09:00:00Z',
  },
];

export const INITIAL_REPAIRS: Repair[] = [
  {
    id: 'rep-1',
    appointment_id: 'app-1',
    vehicle_id: 'veh-1',
    client_id: 'cli-1',
    mechanic_id: 'usr-2',
    mechanic_name: 'Alex Rivera',
    diagnosis: 'Inspected engine oil viscosity: degraded. Slight play in right sway bar link; oil filter seal seated properly.',
    status: 'IN_PROGRESS',
    services: [
      {
        id: 'rsi-1',
        service_id: 'srv-1',
        service_name: 'Synthetic Oil & Filter Service',
        price: 119.0,
        quantity: 1,
      },
    ],
    parts: [
      {
        id: 'rpi-1',
        part_id: 'prt-1',
        part_name: 'Bosch Premium Spin-On Oil Filter',
        part_number: 'BOS-OF-3320',
        unit_price: 19.5,
        quantity: 1,
      },
      {
        id: 'rpi-2',
        part_id: 'prt-3',
        part_name: 'Castrol EDGE 5W-30 LL (5L)',
        part_number: 'CAS-EDGE-5W30',
        unit_price: 58.0,
        quantity: 1,
      },
    ],
    labor_hours: 1.0,
    labor_rate: 90.0,
    total_amount: 286.5,
    notes: 'Customer approved oil and filter; will monitor sway bar link on next inspection.',
    created_at: `${today}T09:15:00Z`,
  },
  {
    id: 'rep-2',
    appointment_id: 'app-5',
    vehicle_id: 'veh-4',
    client_id: 'cli-4',
    mechanic_id: 'usr-2',
    mechanic_name: 'Alex Rivera',
    diagnosis: 'Cylinder 3 misfire code P0303 detected during cold start. Plugs worn down to 1.3mm gap. Alignment toe-in corrected by 0.15 deg.',
    status: 'COMPLETED',
    services: [
      {
        id: 'srv-diag',
        service_id: 'srv-3',
        service_name: 'Comprehensive Computer Diagnostic Scan',
        price: 85.0,
        quantity: 1,
      },
      {
        id: 'srv-spark',
        service_id: 'srv-7',
        service_name: 'Spark Plug & Ignition Coil Renewal',
        price: 180.0,
        quantity: 1,
      },
      {
        id: 'srv-align',
        service_id: 'srv-5',
        service_name: '4-Wheel Laser Precision Alignment',
        price: 135.0,
        quantity: 1,
      },
    ],
    parts: [
      {
        id: 'rpi-ngk',
        part_id: 'prt-4',
        part_name: 'NGK Laser Iridium Spark Plug',
        part_number: 'NGK-SILZKBR8D8S',
        unit_price: 24.0,
        quantity: 4,
      },
    ],
    labor_hours: 2.5,
    labor_rate: 90.0,
    total_amount: 721.0,
    notes: 'Vehicle cleared of all fault codes and road tested. Smooth idle restored.',
    created_at: '2025-09-21T09:30:00Z',
    completed_at: `${yesterday}T16:00:00Z`,
  },
];

export const INITIAL_INVOICES: Invoice[] = [
  {
    id: 'inv-1001',
    invoice_number: 'INV-2025-001',
    repair_id: 'rep-2',
    client_id: 'cli-4',
    vehicle_id: 'veh-4',
    issue_date: yesterday,
    due_date: today,
    items: [
      {
        id: 'itm-1',
        description: 'Comprehensive Computer Diagnostic Scan',
        quantity: 1,
        unit_price: 85.0,
        total: 85.0,
      },
      {
        id: 'itm-2',
        description: 'Spark Plug & Ignition Coil Renewal Labor',
        quantity: 1,
        unit_price: 180.0,
        total: 180.0,
      },
      {
        id: 'itm-3',
        description: '4-Wheel Laser Precision Alignment',
        quantity: 1,
        unit_price: 135.0,
        total: 135.0,
      },
      {
        id: 'itm-4',
        description: 'NGK Laser Iridium Spark Plugs (Set of 4)',
        quantity: 4,
        unit_price: 24.0,
        total: 96.0,
      },
      {
        id: 'itm-5',
        description: 'Workshop Technician Labor (2.5 hrs)',
        quantity: 2.5,
        unit_price: 90.0,
        total: 225.0,
      },
    ],
    subtotal: 721.0,
    tax_rate: 8.0,
    tax_amount: 57.68,
    total_amount: 778.68,
    paid_amount: 778.68,
    remaining_amount: 0.0,
    status: 'PAID',
    notes: 'Paid in full upon pickup by Robert Chen via Credit Card.',
    created_at: `${yesterday}T16:30:00Z`,
  },
  {
    id: 'inv-1002',
    invoice_number: 'INV-2025-002',
    client_id: 'cli-2',
    vehicle_id: 'veh-2',
    issue_date: '2025-09-18',
    due_date: '2025-09-25',
    items: [
      {
        id: 'itm-6',
        description: 'Audi Q5 Brake Inspection & Rear Pads',
        quantity: 1,
        unit_price: 340.0,
        total: 340.0,
      },
      {
        id: 'itm-7',
        description: 'DOT 4 Brake Fluid Flush',
        quantity: 1,
        unit_price: 85.0,
        total: 85.0,
      },
    ],
    subtotal: 425.0,
    tax_rate: 8.0,
    tax_amount: 34.0,
    total_amount: 459.0,
    paid_amount: 200.0,
    remaining_amount: 259.0,
    status: 'PARTIAL',
    notes: 'Initial deposit paid. Balance due upon completion.',
    created_at: '2025-09-18T10:00:00Z',
  },
  {
    id: 'inv-1003',
    invoice_number: 'INV-2025-003',
    client_id: 'cli-3',
    vehicle_id: 'veh-3',
    issue_date: '2025-09-10',
    due_date: '2025-09-17',
    items: [
      {
        id: 'itm-8',
        description: 'Mercedes C300 Electrical Troubleshooting & Sensor',
        quantity: 1,
        unit_price: 380.0,
        total: 380.0,
      },
    ],
    subtotal: 380.0,
    tax_rate: 8.0,
    tax_amount: 30.4,
    total_amount: 410.4,
    paid_amount: 0.0,
    remaining_amount: 410.4,
    status: 'OVERDUE',
    notes: 'Sent second payment reminder to customer.',
    created_at: '2025-09-10T14:00:00Z',
  },
];

export const INITIAL_PAYMENTS: Payment[] = [
  {
    id: 'pay-1',
    invoice_id: 'inv-1001',
    invoice_number: 'INV-2025-001',
    client_name: 'Robert Chen',
    amount: 778.68,
    payment_method: 'CREDIT_CARD',
    date: yesterday,
    reference: 'AUTH-VISA-99120',
    notes: 'Paid at front desk terminal',
    created_at: `${yesterday}T16:45:00Z`,
  },
  {
    id: 'pay-2',
    invoice_id: 'inv-1002',
    invoice_number: 'INV-2025-002',
    client_name: 'David Kim',
    amount: 200.0,
    payment_method: 'BANK_TRANSFER',
    date: '2025-09-18',
    reference: 'WIRE-ACH-38291',
    notes: 'Down payment for scheduled parts ordering',
    created_at: '2025-09-18T11:20:00Z',
  },
];

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 'exp-1',
    category: 'PARTS_SUPPLIES',
    amount: 1420.5,
    date: '2025-09-15',
    description: 'Bulk order OEM filters, Motul brake fluids, and workshop shop towels',
    receipt_ref: 'SUPPLY-PO-8819',
    created_by: 'Marcus Vance',
    created_at: '2025-09-15T09:00:00Z',
  },
  {
    id: 'exp-2',
    category: 'EQUIPMENT',
    amount: 680.0,
    date: '2025-09-08',
    description: 'Snap-on digital torque wrench calibration & hydraulic hoist safety cert',
    receipt_ref: 'TOOL-CAL-029',
    created_by: 'Marcus Vance',
    created_at: '2025-09-08T14:30:00Z',
  },
  {
    id: 'exp-3',
    category: 'UTILITIES',
    amount: 495.2,
    date: '2025-09-05',
    description: 'Workshop commercial electricity, 3-phase compressor power',
    receipt_ref: 'UTIL-ELEC-SEP25',
    created_by: 'Marcus Vance',
    created_at: '2025-09-05T10:00:00Z',
  },
  {
    id: 'exp-4',
    category: 'RENT',
    amount: 3200.0,
    date: '2025-09-01',
    description: 'Monthly commercial garage facility lease (3 bays + office + lot)',
    receipt_ref: 'LEASE-SEP-2025',
    created_by: 'Marcus Vance',
    created_at: '2025-09-01T08:00:00Z',
  },
];
